const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'starpoint-player-login-'))
process.env.DATA_DIR = dataDir
require('ts-node/register/transpile-only')
const auth = require('../src/lib/player-login')
const { getDb } = require('../src/data/db')
const { insertAccountSync, updateAccountSync } = require('../src/data/domains/account')
const { insertDefaultPlayerSync } = require('../src/data/domains/player')
const { insertDeviceBindingSync } = require('../src/data/domains/session')
const { saveAccountDefaultPlayer } = require('../src/data/activeAccount')
const routes = require('../src/routes/cn/playerLogin')
const { installTakeoverUdidGuard } = require('../src/lib/takeover-access')
const { installManagementAuth } = require('../src/lib/management-auth')
const { selectUnnotedAccountIds } = require('../src/lib/admin-account-cleanup')
const Fastify = require('fastify')
const db = getDb(), disconnected = []
auth.initializePlayerLogin(id => disconnected.push(id))
let checks = 0
function check(value, name) { assert.ok(value, name); checks++ }
function legacy(viewer, device) {
    const account = insertAccountSync({ appId: 'wf_cn', idpAlias: '', idpCode: 'leiting', idpId: '', status: 'normal' })
    const player = insertDefaultPlayerSync(account.id)
    saveAccountDefaultPlayer(account.id, player.id)
    insertDeviceBindingSync(device, account.id)
    db.prepare('INSERT INTO sessions(token,account_id,expires,type) VALUES(?,?,?,2)').run(String(viewer), account.id, new Date().toISOString())
    updateAccountSync({ id: account.id, takeoverPassword: 'LegacyPass7', adminNote: '保留原备注' })
    return { account, player, viewer }
}
async function main() {
    const a = auth.registerPlayerLogin('StarTestA', 'PlainPass1', true)
    const accountA = auth.playerAccountByViewer(a.profile.viewer_id)
    check(a.expires_at - Date.now() > 29 * 86400000, 'remember login lasts up to 30 days')
    check(db.prepare('SELECT password FROM player_login_credentials WHERE account_id=?').get(accountA).password === 'PlainPass1', 'explicit plaintext requirement')
    const count = db.prepare('SELECT count(*) n FROM accounts').get().n
    assert.throws(() => auth.registerPlayerLogin('STARTesTA', 'OtherPass1', false), auth.PlayerLoginError)
    check(db.prepare('SELECT count(*) n FROM accounts').get().n === count, 'duplicate registration rolled back account and save')
    assert.throws(() => auth.loginPlayer('startesta', 'wrongpw', false), auth.PlayerLoginError)
    check(auth.readPlayerLoginSession(a.token), 'wrong password preserves active session')
    const second = auth.loginPlayer('startesta', 'PlainPass1', false)
    check(!auth.readPlayerLoginSession(a.token) && auth.readPlayerLoginSession(second.token), 'new login revokes previous device')
    check(second.expires_at - Date.now() < 13 * 3600000, 'non-remembered session has short absolute expiry')
    auth.logoutPlayer(a.token)
    check(auth.readPlayerLoginSession(second.token), 'stale logout cannot revoke new device')
    const old = legacy(423456781, 7001), other = legacy(423456782, 7002)
    const beforePlayer = db.prepare('SELECT * FROM players WHERE id=?').get(old.player.id)
    const preview = auth.previewPlayerClaim({ viewer_id: old.viewer, inherit_password: 'LegacyPass7' })
    const bound = auth.bindPlayerLogin(preview.proof, 'OldSaveA', 'NewPlain7', true)
    check(bound.profile.viewer_id === old.viewer && auth.playerAccountByViewer(old.viewer) === old.account.id, 'binding preserves original account and viewer')
    assert.deepEqual(db.prepare('SELECT * FROM players WHERE id=?').get(old.player.id), beforePlayer); checks++
    check(db.prepare('SELECT admin_note FROM accounts WHERE id=?').get(old.account.id).admin_note === '保留原备注', 'binding preserves admin note')
    check(db.prepare('SELECT 1 FROM accounts WHERE id=?').get(other.account.id), 'binding never deletes other saves')
    assert.throws(() => auth.bindPlayerLogin(preview.proof, 'AnotherA', 'OtherPass1', true), auth.PlayerLoginError)
    assert.throws(() => auth.previewPlayerClaim({ viewer_id: old.viewer, inherit_password: 'LegacyPass7' }), auth.PlayerLoginError)
    const code = auth.createPlayerLoginCode(other.viewer, 'bind')
    const codePreview = auth.previewPlayerClaim({ code: code.code })
    const byCode = auth.bindPlayerLogin(codePreview.proof, 'CodeUserA', 'CodePass7', true)
    check(byCode.profile.viewer_id === other.viewer, 'one-time admin code binds designated save')
    assert.throws(() => auth.previewPlayerClaim({ code: code.code }), auth.PlayerLoginError)
    const stale = legacy(423456783, 7003)
    const stalePreview = auth.previewPlayerClaim({ viewer_id: stale.viewer, inherit_password: 'LegacyPass7' })
    updateAccountSync({ id: stale.account.id, takeoverPassword: 'ChangedPass8' })
    assert.throws(() => auth.bindPlayerLogin(stalePreview.proof, 'StaleUser', 'PlainPass1', true), auth.PlayerLoginError)
    check(!auth.playerLoginManaged(stale.account.id), 'changed inheritance password invalidates pending proof')
    const reset = auth.createPlayerLoginCode(old.viewer, 'reset')
    auth.resetPlayerLoginPassword(reset.code, 'ResetPlain8')
    check(!auth.readPlayerLoginSession(bound.token), 'password reset revokes every previous session')
    assert.throws(() => auth.resetPlayerLoginPassword(reset.code, 'ResetPlain9'), auth.PlayerLoginError)
    const afterReset = auth.loginPlayer('oldsavea', 'ResetPlain8', true)
    check(afterReset.profile.viewer_id === old.viewer, 'reset preserves original save')
    check(!auth.playerSocketAllowed(old.viewer, '') && auth.playerSocketAllowed(old.viewer, afterReset.token), 'managed TCP handshake requires session')
    db.prepare("UPDATE accounts SET status='banned' WHERE id=?").run(old.account.id)
    assert.throws(() => auth.loginPlayer('oldsavea', 'ResetPlain8', true), auth.PlayerLoginError)
    check(!auth.readPlayerLoginSession(afterReset.token), 'banned account session denied')
    db.prepare("UPDATE accounts SET status='normal' WHERE id=?").run(old.account.id)
    check(selectUnnotedAccountIds([{ id: 1, username: 'bound' }, { id: 2, adminNote: 'keep' }]).join(',') === '1', 'unnoted cleanup depends only on account notes, including registered accounts')
    process.env.ADMIN_PANEL_PASSWORD = 'test-management-only'
    const app = Fastify({ logger: false })
    app.addHook('onSend', (_request, reply, payload, done) => {
        if (reply.getHeader('content-type') === 'application/x-msgpack' && typeof payload === 'object') done(null, JSON.stringify(payload))
        else done(null, payload)
    })
    installManagementAuth(app)
    routes.installPlayerLoginGuard(app); installTakeoverUdidGuard(app)
    await app.register(routes.default)
    await app.register(require('../src/routes/web_api/server').default, { prefix: '/api/server' })
    await app.register(require('../src/routes/cn/tool').default, { prefix: '/api/index.php/tool' })
    await app.register(require('../src/routes/cn/takeOver').default, { prefix: '/api/index.php' })
    app.post('/api/index.php/test-protected', async () => ({ allowed: true }))
    await app.ready()
    const post = (url, payload, headers = {}) => app.inject({ method: 'POST', url, payload, headers })
    let res = await post('/api/server/account/player-login-code', { viewer_id: stale.viewer, purpose: 'bind' })
    check(res.statusCode === 401, 'admin code generation requires management authentication')
    const adminLogin = await post('/admin-login', { password: 'test-management-only' })
    const adminCookie = adminLogin.headers['set-cookie'].split(';')[0]
    res = await post('/api/server/account/player-login-code', { viewer_id: stale.viewer, purpose: 'bind' }, { cookie: adminCookie })
    check(res.json().ok && res.json().data.profile.viewer_id === stale.viewer, 'authenticated administrator can generate designated bind code')
    const adminPage = await app.inject({ url: '/admin/player-login', headers: { cookie: adminCookie } })
    check(adminPage.statusCode === 200 && adminPage.body.includes('生成验证码'), 'administrator code page is accessible after login')
    const adminAccounts = await app.inject({ url: '/api/server/accounts', headers: { cookie: adminCookie } })
    const managedRow = adminAccounts.json().find(row => row.id === old.account.id)
    check(managedRow.loginUsername === 'oldsavea' && managedRow.playerLogin.bound && managedRow.playerLogin.sessionExpiresAt === afterReset.expires_at, 'admin overview exposes login state and absolute expiry')
    check(managedRow.note === '保留原备注' && managedRow.bindings[0].deviceId === 7001, 'admin overview preserves account note and historical device')
    check(!adminAccounts.body.includes(afterReset.token) && !adminAccounts.body.includes('ResetPlain8'), 'admin overview never returns credentials')
    const unboundRow = adminAccounts.json().find(row => row.id === stale.account.id)
    check(!unboundRow.loginUsername && !unboundRow.playerLogin.bound && unboundRow.playerLogin.sessionExpiresAt === null, 'unbound admin row has no login account or login session')
    const resetFixture = legacy(423456784, 7004)
    const resetPreview = auth.previewPlayerClaim({ viewer_id: resetFixture.viewer, inherit_password: 'LegacyPass7' })
    const resetSession = auth.bindPlayerLogin(resetPreview.proof, 'ResetApiUser', 'BeforeReset8', true)
    const resetPlayerBefore = db.prepare('SELECT * FROM players WHERE id=?').get(resetFixture.player.id)
    res = await post('/api/server/account/player-login-code', { viewer_id: resetFixture.viewer, purpose: 'reset' })
    check(res.statusCode === 401, 'anonymous administrator reset-code request rejected')
    res = await post('/api/server/account/player-login-code', { viewer_id: stale.viewer, purpose: 'reset' }, { cookie: adminCookie })
    check(!res.json().ok && res.json().message.includes('尚未绑定'), 'unbound save cannot receive a login-password reset code')
    const issueReset = () => post('/api/server/account/player-login-code', { viewer_id: resetFixture.viewer, purpose: 'reset' }, { cookie: adminCookie })
    res = await issueReset()
    const replacedResetCode = res.json().data.code
    check(res.json().ok && res.json().data.profile.viewer_id === resetFixture.viewer && res.json().data.profile.username === 'resetapiuser', 'authenticated reset-code API targets the correct login and UID')
    check(res.json().data.expires_at > Date.now() + 14 * 60000 && res.json().data.expires_at <= Date.now() + 15 * 60000, 'reset-code API returns a fifteen-minute validity window')
    check(auth.readPlayerLoginSession(resetSession.token), 'generating reset code alone does not sign player out')
    res = await issueReset()
    const apiResetCode = res.json().data.code
    res = await post('/player-auth/reset-password', { code: replacedResetCode, password: 'AfterReset8' })
    check(!res.json().ok && auth.readPlayerLoginSession(resetSession.token), 'new reset code replaces old code without changing credentials')
    res = await post('/player-auth/reset-password', { code: apiResetCode, password: 'short' })
    check(!res.json().ok && db.prepare('SELECT consumed_at FROM player_login_codes WHERE code=?').get(apiResetCode).consumed_at === null, 'invalid new password does not consume reset code')
    const resetDisconnectStart = disconnected.length
    res = await post('/player-auth/reset-password', { code: apiResetCode, password: 'AfterReset8' })
    check(res.json().ok && res.json().data.username === 'resetapiuser', 'player reset-password HTTP endpoint accepts administrator code')
    check(!auth.readPlayerLoginSession(resetSession.token) && disconnected.slice(resetDisconnectStart).includes(resetFixture.viewer), 'HTTP password reset revokes old credential and disconnects old transport')
    res = await post('/player-auth/login', { username: 'resetapiuser', password: 'BeforeReset8', remember: true })
    check(!res.json().ok, 'old password rejected after HTTP password reset')
    res = await post('/player-auth/login', { username: 'resetapiuser', password: 'AfterReset8', remember: true })
    const resetRelogin = res.json().data
    check(res.json().ok && resetRelogin.profile.viewer_id === resetFixture.viewer, 'new password returns same original UID through HTTP login')
    check(resetRelogin.udid !== resetSession.udid && /^[a-f0-9]{32}$/.test(resetRelogin.udid), 'fresh login issues random UDID rather than permanent account device ID')
    res = await post('/player-auth/resume', { token: resetRelogin.token })
    check(res.json().ok && res.json().data.udid === resetRelogin.udid, 'remembered-session resume keeps that session UDID')
    assert.deepEqual(db.prepare('SELECT * FROM players WHERE id=?').get(resetFixture.player.id), resetPlayerBefore); checks++
    check(db.prepare('SELECT admin_note FROM accounts WHERE id=?').get(resetFixture.account.id).admin_note === '保留原备注'
        && db.prepare('SELECT account_id FROM device_bindings WHERE device_id=?').get(7004).account_id === resetFixture.account.id, 'HTTP reset preserves note and historical device binding')
    res = await post('/player-auth/reset-password', { code: apiResetCode, password: 'ReplayReset8' })
    check(!res.json().ok && auth.readPlayerLoginSession(resetRelogin.token), 'consumed reset code cannot be replayed or revoke new session')
    res = await issueReset()
    const expiredResetCode = res.json().data.code
    db.prepare('UPDATE player_login_codes SET expires_at=? WHERE code=?').run(Date.now() - 1, expiredResetCode)
    res = await post('/player-auth/reset-password', { code: expiredResetCode, password: 'ExpiredReset8' })
    check(!res.json().ok && auth.readPlayerLoginSession(resetRelogin.token), 'expired reset code cannot change the login password')
    res = await post('/api/server/account/takeover-password/reset', { account_id: old.account.id, confirm: 'RESET_TAKEOVER_PASSWORD' }, { cookie: adminCookie })
    check(res.statusCode === 409, 'bound save cannot mistakenly reset the obsolete inheritance password')
    res = await post('/player-auth/resume', { token: '0'.repeat(64) })
    check(res.json().code === 'SESSION_INVALID', 'only confirmed invalid sessions receive an invalidation code')
    res = await post('/api/index.php/test-protected', { viewer_id: old.viewer })
    check(res.json().data_headers.result_code === 516, 'legacy UID cannot access bound save')
    res = await post('/api/index.php/test-protected', { viewer_id: old.viewer }, { 'x-sp-session': afterReset.token, udid: afterReset.udid })
    check(res.json().allowed, 'authenticated game request accepted')
    const switchDisconnectStart = disconnected.length
    res = await post('/player-auth/resume', { token: second.token, previous_token: afterReset.token })
    check(res.json().ok && res.json().data.expires_at === second.expires_at, 'switching to a remembered account keeps its original expiry')
    check(auth.readPlayerLoginSession(second.token) && auth.readPlayerLoginSession(afterReset.token), 'switching preserves both account credentials')
    check(disconnected.slice(switchDisconnectStart).includes(old.viewer), 'switching disconnects previous account transport')
    res = await post('/player-auth/resume', { token: afterReset.token, previous_token: second.token })
    check(res.json().ok && res.json().data.profile.viewer_id === old.viewer, 'switching back needs no password')
    const beforeFailedSwitch = disconnected.length
    res = await post('/player-auth/resume', { token: 'f'.repeat(64), previous_token: afterReset.token })
    check(res.json().code === 'SESSION_INVALID' && disconnected.length === beforeFailedSwitch, 'failed switch leaves active account transport intact')
    res = await post('/api/index.php/test-protected', { viewer_id: old.viewer }, { 'x-sp-session': second.token, udid: afterReset.udid })
    check(res.json().data_headers.result_code === 516, 'session cannot access another save')
    res = await post('/api/index.php/test-protected', { viewer_id: 999999999 }, { 'x-sp-session': afterReset.token })
    check(res.json().data_headers.result_code === 516, 'valid token cannot authenticate an unknown viewer')
    const scratch = auth.registerPlayerLogin('RemoveOnly', 'RemovePass7', true)
    res = await post('/player-auth/logout', { token: scratch.token })
    check(res.json().ok && !auth.readPlayerLoginSession(scratch.token) && auth.readPlayerLoginSession(afterReset.token) && auth.readPlayerLoginSession(second.token), 'removing one saved login leaves all other accounts valid')
    res = await post('/api/index.php/take_over/take_over_by_take_over_data', { viewer_id: other.viewer, input_viewer_id: stale.viewer, input_password: 'ChangedPass8', device_id: 7002 }, { 'x-sp-session': byCode.token, udid: byCode.udid })
    check(res.json().data_headers.result_code === 516 && db.prepare('SELECT 1 FROM accounts WHERE id=?').get(other.account.id), 'legacy transfer cannot delete registered source account')
    res = await post('/api/index.php/tool/signup', { device_id: 7001 })
    check(res.json().data_headers.result_code === 516, 'device-only signup cannot reclaim managed save')
    res = await post('/api/index.php/tool/signup', { device_id: 7002 }, { 'x-sp-session': second.token })
    check(res.json().data_headers.viewer_id === second.profile.viewer_id, 'authenticated signup uses selected account and preserves unrelated device save')
    for (let i = 0; i < 31; i++) res = await post('/player-auth/login', { username: 'startesta', password: 'wrongpw' })
    check(res.json().message.includes('频繁'), 'login attempts rate limited')
    res = await post('/player-auth/resume', { token: afterReset.token })
    check(res.json().ok, 'password attempt limit does not consume the separate remembered-session budget')
    check(disconnected.length >= 6, 'session replacements and reset revoke live transports')
    await app.close()
    const realNow = Date.now, simulatedNow = realNow()
    const expiredClaim = db.prepare('INSERT INTO player_login_claims(proof,account_id,source,original_value,expires_at) VALUES(?,?,?, ?,?)')
    db.transaction(() => { for (let i = 0; i < 250; i++) expiredClaim.run('maintenance' + i, accountA, 'inherit', 'fixture', simulatedNow - 1) })()
    try {
        Date.now = () => simulatedNow + 61000
        auth.maintainPlayerLogin()
        const remainingClaims = () => db.prepare("SELECT count(*) n FROM player_login_claims WHERE proof LIKE 'maintenance%'").get().n
        check(remainingClaims() === 150, 'maintenance deletes at most 100 expired rows per table')
        auth.maintainPlayerLogin()
        check(remainingClaims() === 150, 'maintenance does not rerun on every authentication action')
    } finally { Date.now = realNow }
    db.prepare('UPDATE player_login_sessions SET expires_at=? WHERE token=?').run(Date.now() - 1, second.token)
    check(!auth.readPlayerLoginSession(second.token), 'server enforces absolute expiration')
    console.log(`PASS player-login integration: ${checks} assertions plus rejected operations; isolated database only.`)
}
main().catch(error => { console.error(error); process.exitCode = 1 }).finally(async () => {
    await require('../src/multi/npc/player-party-pool').stopQuestNpcPartyPoolWorker()
    getDb().close()
    const resolved = path.resolve(dataDir)
    assert.ok(resolved.startsWith(path.resolve(os.tmpdir()) + path.sep))
    fs.rmSync(resolved, { recursive: true, force: true })
    setImmediate(() => process.exit(process.exitCode || 0))
})
