#!/usr/bin/env python3
"""Stage the Thunder Dragon / Abyss gacha content on top of client 1.4.78.

The shared release was built against another version line and contains full
copies of several master tables.  Installing those copies directly would drop
locally-owned characters, shops and the Fantasy equipment ``trimmed_image``
rows.  This importer therefore treats ``ownership.json`` as a whitelist:

* the current 1.4.78 archive chain is the base;
* only explicitly-owned outer orderedmap keys are appended;
* all unrelated rows remain byte-for-byte identical;
* genuinely new resources are staged unchanged;
* the two shared item-atlas replacements are accepted only when the current
  base and incoming hashes match the reviewed release.

The output is an ignored working store, not a published diff archive.  The
active manifest and ``.cdn`` are read-only and are never modified.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import re
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import wf_mod_tool as core
import wf_store_materialize as materialize


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "assets" / "asset-patch" / "production"
EXPECTED_PACKAGE_SHA256 = (
    "5c540fe63937328f14be6006701ff635806e465ebe435e0615bcce1c47feb918"
)
EXPECTED_RELEASE_ID = (
    "sha256:0b74b4ecb6aa44c98c5f386fbc7c1d84ee2785f48a3e785c0d04b2311ab6a262"
)
EXPECTED_PAYLOAD_SHA256 = (
    "c8fee9e5eb361702b7287c3bac3e4882b45c35e0b143575a3718f5fe447c8952"
)
EXPECTED_TAIL = "1.4.78"
REPORT_NAME = "thunder-dragon-abyss-gacha-draft-report.json"

STORE_DIRECTORY = {
    "common": "upload",
    "medium": "medium_upload",
    "android": "android_upload",
}
MEMBER_RE = re.compile(
    r"^production/(upload|medium_upload|android_upload)/"
    r"([0-9a-f]{2}/[0-9a-f]{38})$"
)
DIRECTORY_TO_ROOT = {value: key for key, value in STORE_DIRECTORY.items()}

# One ownership record corresponds to one outer orderedmap key.  Tables that
# are server-only JSON mirrors intentionally do not appear here.
TABLE_ALIAS_TO_LOGICAL = {
    "ability": "master/ability/ability.orderedmap",
    "leader_ability": "master/ability/leader_ability.orderedmap",
    "character": "master/character/character.orderedmap",
    "character_gacha_sound": "master/character/character_gacha_sound.orderedmap",
    "character_speech": "master/character/character_speech.orderedmap",
    "character_status": "master/character/character_status.orderedmap",
    "character_text": "master/character/character_text.orderedmap",
    "full_shot_image_attribute": (
        "master/character/full_shot_image_attribute.orderedmap"
    ),
    "unique_condition": "master/character/unique_condition.orderedmap",
    "gacha": "master/gacha/gacha.orderedmap",
    "gacha_feature_content": "master/gacha/gacha_feature_content.orderedmap",
    "cnmod_abyss_limited_gacha_character_3": (
        "master/gacha_odds/cnmod_abyss_limited_gacha_character_3.orderedmap"
    ),
    "cnmod_abyss_limited_gacha_character_4": (
        "master/gacha_odds/cnmod_abyss_limited_gacha_character_4.orderedmap"
    ),
    "cnmod_abyss_limited_gacha_character_5": (
        "master/gacha_odds/cnmod_abyss_limited_gacha_character_5.orderedmap"
    ),
    "cnmod_abyss_limited_gacha_rarity": (
        "master/gacha_odds/cnmod_abyss_limited_gacha_rarity.orderedmap"
    ),
    "character_image": "master/generated/character_image.orderedmap",
    "mana_board": "master/generated/mana_board.orderedmap",
    "trimmed_image": "master/generated/trimmed_image.orderedmap",
    "item": "master/item/item.orderedmap",
    "mana_board2_open_condition": (
        "master/mana_board/mana_board2_open_condition.orderedmap"
    ),
    "mana_node": "master/mana_board/mana_node.orderedmap",
    "upskill": "master/mana_board/upskill.orderedmap",
    "cnmod_rogue_event": "master/quest/event/cnmod_rogue_event.orderedmap",
    "rich_text_html": "master/rich_text/rich_text_html.orderedmap",
    "event_item_shop": "master/shop/event_item_shop.orderedmap",
    "action_skill": "master/skill/action_skill.orderedmap",
    "skill_preview_character": (
        "master/skill_preview/skill_preview_character.orderedmap"
    ),
    "character_stance_detail": (
        "master/stance_detail/character_stance_detail.orderedmap"
    ),
}

# These ownership paths describe server-side JSON mirrors generated by the
# author's content-sync framework.  They are deliberately merged into this
# repository separately instead of being expected inside the client archives.
SERVER_METADATA_PATHS = {
    "cdndata/character.json",
    "cdndata/character_text.json",
    "cdndata/gacha.json",
    "cdndata/gacha_feature_content.json",
    "character.json",
    "event_item_shop.json",
    "event_item_shop_id_map.json",
    "gacha.json",
    "item_ids.json",
    "mana_node.json",
    "rogue_event.json",
}

# The release's acceptedAssetReplacements hashes describe its already-patched
# input, not our pre-merge base.  Pin both sides that were reviewed locally so
# a later atlas modification produces a conflict rather than a silent rollback.
ACCEPTED_REPLACEMENTS = {
    ("common", "item/sprite_sheet.atlas.amf3.deflate"): {
        "current": "140b06b1e592fb698d2694739de62e680f73860aa898afdb9b6c00087765455b",
        "incoming": "34526c17de84f53e341324a3dd4ea63915987255f118e669ccda280db8abb2af",
    },
    ("common", "item/sprite_sheet.png"): {
        "current": "b694f71790331af7bbc374bc8f75ccb38cfe48b072b700479ca85cca70ce74fc",
        "incoming": "13039ef5b3fe8429a4f356dc770620c4f3ccb273ab960a81a06d4fe0960abfc7",
    },
}


@dataclass(frozen=True)
class IncomingRelease:
    ownership: dict[str, Any]
    files: dict[tuple[str, str], bytes]
    logical_by_relative: dict[str, str]


@dataclass(frozen=True)
class MergeResult:
    payload: bytes
    base_keys: tuple[str, ...]
    added_keys: tuple[str, ...]


def sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _find_suffix(names: list[str], suffix: str) -> str:
    matches = [name for name in names if name.replace("\\", "/").endswith(suffix)]
    if len(matches) != 1:
        raise ValueError(f"expected one {suffix!r}, got {matches}")
    return matches[0]


def _read_json_bytes(payload: bytes, label: str) -> dict[str, Any]:
    try:
        value = json.loads(payload.decode("utf-8-sig"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"invalid JSON in {label}: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"{label} must contain a JSON object")
    return value


def load_incoming_release(package_path: Path) -> IncomingRelease:
    package_payload = package_path.read_bytes()
    if sha256(package_payload) != EXPECTED_PACKAGE_SHA256:
        raise ValueError("shared package SHA-256 does not match the reviewed 1.1.5 release")

    with zipfile.ZipFile(io.BytesIO(package_payload)) as package:
        release_name = _find_suffix(
            package.namelist(), "content/fresh-install.wf-release.zip"
        )
        release_payload = package.read(release_name)

    with zipfile.ZipFile(io.BytesIO(release_payload)) as release:
        ownership_name = _find_suffix(release.namelist(), "wf-release-v1/ownership.json")
        manifest_name = _find_suffix(
            release.namelist(), "wf-release-v1/release-manifest.json"
        )
        ownership = _read_json_bytes(release.read(ownership_name), ownership_name)
        release_manifest = _read_json_bytes(release.read(manifest_name), manifest_name)
        if release_manifest.get("releaseId") != EXPECTED_RELEASE_ID:
            raise ValueError("unexpected wf-release releaseId")
        components = release_manifest.get("files")
        if not isinstance(components, list) or len(components) != 1:
            raise ValueError("wf-release must contain exactly one client payload")
        payload_relative = components[0].get("path")
        if not isinstance(payload_relative, str):
            raise ValueError("wf-release payload path is missing")
        payload_name = _find_suffix(
            release.namelist(), f"wf-release-v1/{payload_relative}"
        )
        payload = release.read(payload_name)
        if sha256(payload) != EXPECTED_PAYLOAD_SHA256:
            raise ValueError("client payload SHA-256 does not match the reviewed release")

    with zipfile.ZipFile(io.BytesIO(payload)) as overlay:
        patch_manifest = _read_json_bytes(
            overlay.read("patch-manifest.json"), "patch-manifest.json"
        )
        archives = patch_manifest.get("archives")
        if not isinstance(archives, list) or len(archives) != 3:
            raise ValueError("client payload must contain three layer archives")
        files: dict[tuple[str, str], bytes] = {}
        for descriptor in archives:
            if not isinstance(descriptor, dict):
                raise ValueError("invalid client archive descriptor")
            root_name = descriptor.get("layer")
            relative_path = descriptor.get("relativePath")
            if root_name not in STORE_DIRECTORY or not isinstance(relative_path, str):
                raise ValueError("invalid client archive root/path")
            archive_payload = overlay.read(relative_path)
            if sha256(archive_payload) != descriptor.get("sha256"):
                raise ValueError(f"client archive hash mismatch: {relative_path}")
            with zipfile.ZipFile(io.BytesIO(archive_payload)) as archive:
                for info in archive.infolist():
                    if info.is_dir() or info.filename in (".empty", ".empty/"):
                        continue
                    normalized = info.filename.replace("\\", "/")
                    match = MEMBER_RE.fullmatch(normalized)
                    if match is None:
                        raise ValueError(f"unsafe/unexpected client member: {normalized}")
                    member_root = DIRECTORY_TO_ROOT[match.group(1)]
                    if member_root != root_name:
                        raise ValueError(
                            f"archive layer/member root mismatch: {relative_path}!{normalized}"
                        )
                    key = (member_root, match.group(2))
                    if key in files:
                        raise ValueError(f"duplicate client member: {key}")
                    files[key] = archive.read(info)

    paths = ownership.get("paths")
    if not isinstance(paths, list) or not all(isinstance(path, str) for path in paths):
        raise ValueError("ownership paths must be a string array")
    logical_by_relative: dict[str, str] = {}
    for logical in paths:
        digest = core.sha1_path(logical)
        relative = f"{digest[:2]}/{digest[2:]}"
        previous = logical_by_relative.setdefault(relative, logical)
        if previous != logical:
            raise ValueError(f"logical path hash collision: {previous} / {logical}")

    unmapped = sorted(relative for _root, relative in files if relative not in logical_by_relative)
    if unmapped:
        raise ValueError(f"payload members missing from ownership: {unmapped[:5]}")
    return IncomingRelease(ownership, files, logical_by_relative)


def owned_table_keys(ownership: dict[str, Any]) -> dict[str, tuple[str, ...]]:
    records = ownership.get("records")
    paths = ownership.get("paths")
    if not isinstance(records, list) or not isinstance(paths, list):
        raise ValueError("ownership records/paths are missing")
    result: dict[str, list[str]] = {}
    for record in records:
        if not isinstance(record, str) or ":" not in record:
            raise ValueError(f"invalid ownership record: {record!r}")
        alias, key = record.split(":", 1)
        logical = TABLE_ALIAS_TO_LOGICAL.get(alias)
        if logical is None:
            continue
        keys = result.setdefault(logical, [])
        if key in keys:
            raise ValueError(f"duplicate ownership record: {record}")
        keys.append(key)
    for logical in result:
        if logical not in paths:
            raise ValueError(f"owned table is absent from ownership paths: {logical}")
    return {logical: tuple(keys) for logical, keys in result.items()}


def merge_owned_records(
    base_payload: bytes | None,
    incoming_payload: bytes,
    logical: str,
    keys: tuple[str, ...],
) -> MergeResult:
    incoming = core.read_orderedmap_raw_rows_from_bytes(incoming_payload, logical)
    incoming_rows = dict(zip(incoming.keys, incoming.rows))
    missing = [key for key in keys if key not in incoming_rows]
    if missing:
        raise ValueError(f"incoming {logical} is missing owned keys: {missing}")

    if base_payload is None:
        base = core.OrderedMap(logical, [], [], Path(logical))
    else:
        base = core.read_orderedmap_raw_rows_from_bytes(base_payload, logical)
    original_keys = tuple(base.keys)
    original_rows = tuple(base.rows)
    current = dict(zip(base.keys, base.rows))
    additions: list[str] = []
    for key in keys:
        row = incoming_rows[key]
        if key in current:
            if current[key] != row:
                raise ValueError(f"owned record conflicts with current 1.4.78: {logical}:{key}")
            continue
        base.keys.append(key)
        base.rows.append(row)
        current[key] = row
        additions.append(key)

    payload = core.build_orderedmap_raw_rows(base)
    verified = core.read_orderedmap_raw_rows_from_bytes(payload, logical)
    if tuple(verified.keys[: len(original_keys)]) != original_keys:
        raise RuntimeError(f"existing key order changed in {logical}")
    if tuple(verified.rows[: len(original_rows)]) != original_rows:
        raise RuntimeError(f"existing raw rows changed in {logical}")
    if tuple(verified.keys[len(original_keys) :]) != tuple(additions):
        raise RuntimeError(f"new keys were not appended canonically in {logical}")
    return MergeResult(payload, original_keys, tuple(additions))


class CurrentStoreResolver:
    def __init__(self, cdn_root: Path, repo_root: Path, tail: str):
        self.plan = materialize._build_plan(  # type: ignore[attr-defined]
            cdn_root, repo_root, tail, False
        )
        if self.plan.tail != tail:
            raise ValueError(f"materialized tail mismatch: {self.plan.tail} != {tail}")

    def read(self, root: str, relative: str) -> bytes | None:
        entry = self.plan.entries.get((root, relative))
        if entry is None:
            return None
        with zipfile.ZipFile(entry.zip_path) as archive:
            info = archive.getinfo(entry.name)
            if info.CRC != entry.crc or info.file_size != entry.size:
                raise ValueError(f"planned archive member changed: {entry.zip_path}!{entry.name}")
            return archive.read(info)


def _replacement_allowed(
    root: str, logical: str, current: bytes, incoming: bytes
) -> bool:
    receipt = ACCEPTED_REPLACEMENTS.get((root, logical))
    if receipt is None:
        return False
    if sha256(current) != receipt["current"]:
        raise ValueError(f"reviewed current replacement hash changed: {logical}")
    if sha256(incoming) != receipt["incoming"]:
        raise ValueError(f"reviewed incoming replacement hash changed: {logical}")
    return True


def build_staged_files(
    release: IncomingRelease,
    resolver: CurrentStoreResolver,
) -> tuple[dict[tuple[str, str], bytes], dict[str, Any]]:
    table_keys = owned_table_keys(release.ownership)
    staged: dict[tuple[str, str], bytes] = {}
    report_tables: dict[str, Any] = {}
    replacements: list[str] = []
    new_resources: list[str] = []

    for (root, relative), incoming in sorted(release.files.items()):
        logical = release.logical_by_relative[relative]
        current = resolver.read(root, relative)
        keys = table_keys.get(logical)
        if keys is not None:
            if root != "common":
                raise ValueError(f"master table is not in common root: {root}:{logical}")
            merged = merge_owned_records(current, incoming, logical, keys)
            staged[(root, relative)] = merged.payload
            report_tables[logical] = {
                "baseRows": len(merged.base_keys),
                "addedKeys": list(merged.added_keys),
                "sha256": sha256(merged.payload),
            }
            continue

        if current is not None and current != incoming:
            if not _replacement_allowed(root, logical, current, incoming):
                raise ValueError(f"unreviewed existing asset replacement: {root}:{logical}")
            replacements.append(logical)
        elif current is None:
            new_resources.append(logical)
        staged[(root, relative)] = incoming

    # Client-owned master tables must all have produced a staged member.
    for logical in table_keys:
        digest = core.sha1_path(logical)
        relative = f"{digest[:2]}/{digest[2:]}"
        if ("common", relative) not in staged:
            raise ValueError(f"owned master table is absent from client payload: {logical}")

    payload_logicals = {
        release.logical_by_relative[relative] for _root, relative in release.files
    }
    missing_paths = set(release.ownership.get("paths", ())) - payload_logicals
    unexpected_missing = sorted(missing_paths - SERVER_METADATA_PATHS)
    if unexpected_missing:
        raise ValueError(f"ownership paths missing from payload: {unexpected_missing}")

    report = {
        "schemaVersion": 1,
        "baseVersion": EXPECTED_TAIL,
        "published": False,
        "sourcePackageSha256": EXPECTED_PACKAGE_SHA256,
        "files": len(staged),
        "bytes": sum(len(payload) for payload in staged.values()),
        "roots": {
            root: sum(member_root == root for member_root, _relative in staged)
            for root in STORE_DIRECTORY
        },
        "tables": report_tables,
        "acceptedReplacements": sorted(replacements),
        "newResources": sorted(new_resources),
        "serverMetadataMergedSeparately": sorted(missing_paths),
    }
    return staged, report


def _assert_safe_output(output_root: Path) -> None:
    resolved = output_root.resolve()
    if any(part.lower() == ".cdn" for part in resolved.parts):
        raise ValueError("refusing to write staged content under .cdn")
    if resolved == ROOT.resolve():
        raise ValueError("refusing to use the repository root as output")


def write_staged_files(
    output_root: Path,
    staged: dict[tuple[str, str], bytes],
    report: dict[str, Any],
) -> None:
    _assert_safe_output(output_root)
    for (root, relative), payload in sorted(staged.items()):
        target = output_root / STORE_DIRECTORY[root] / Path(relative)
        target.parent.mkdir(parents=True, exist_ok=True)
        temporary = target.with_name(target.name + ".tmp-cnmod-thunder")
        if temporary.exists():
            raise FileExistsError(f"stale staging temporary file: {temporary}")
        temporary.write_bytes(payload)
        os.replace(temporary, target)
        if target.read_bytes() != payload:
            raise RuntimeError(f"staged file readback mismatch: {target}")
    report_path = output_root / REPORT_NAME
    temporary_report = report_path.with_suffix(".json.tmp-cnmod-thunder")
    if temporary_report.exists():
        raise FileExistsError(f"stale staging temporary file: {temporary_report}")
    temporary_report.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    os.replace(temporary_report, report_path)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--package", required=True, type=Path)
    parser.add_argument("--cdn", required=True, type=Path)
    parser.add_argument("--repo", type=Path, default=ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--tail", default=EXPECTED_TAIL)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="write the ignored working store; otherwise perform a read-only preflight",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.tail != EXPECTED_TAIL:
        raise ValueError(f"this reviewed importer requires client tail {EXPECTED_TAIL}")
    release = load_incoming_release(args.package)
    resolver = CurrentStoreResolver(args.cdn, args.repo, args.tail)
    staged, report = build_staged_files(release, resolver)
    if args.apply:
        write_staged_files(args.output, staged, report)
    print(json.dumps(report, ensure_ascii=False, indent=2))
    print(f"mode: {'staged' if args.apply else 'preflight-only'}")
    if args.apply:
        print(f"working store: {args.output.resolve()}")
    else:
        print("active manifest and working store were not changed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, zipfile.BadZipFile) as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2)
